export const CREATE_EVENT_REQUEST = 'CREATE_EVENT_REQUEST'
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS'
export const CREATE_EVENT_FAILURE = 'CREATE_EVENT_FAILURE'

export const END_EVENT_REQUEST = 'END_EVENT_REQUEST'
export const END_EVENT_SUCCESS = 'END_EVENT_SUCCESS'
export const END_EVENT_FAILURE = 'END_EVENT_FAILURE'
